web/config/routes.rb
Web::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  # TODO put in authorization so can't hit routes like /settings (obviously)
  constraints subdomain: "api" do
    get "/" => "static#api", as: :api
    get "/users" => "users#index", format: :json
    get "/users/:id" => "users#show", format: :json
    get "/apps/:id" => "apps#show", format: :json
  end
  authenticated :user do
    root to: "static#dashboard"
  end
  root to: "static#index"
  get  "/about" => "static#about", as: :about
  get  "/faq" => "static#faq", as: :faq
  get  "/search" => "static#search", as: :search
  get  "/trust" => "static#trust", as: :trust
  get  "/contact" => "static#contact", as: :contact
  post "/contact" => "static#send_contact_email", as: :send_contact_email
  devise_for :users, controllers: {confirmations: "users/confirmations"}
  resources :users, except: [:edit, :update] do
    # TODO scope keys? so its "/keys/:id"
    resources :keys, except: [:new, :create]
    resources :apps, except: [:new, :create]
  end
  get "/apps/:id" => "apps#show", as: :app
  get "/keys/:id/confirm/:confirmation_token" => "keys#confirm", as: :key_confirmation
  get "/apps/:id/mini" => "apps#mini", as: :show_app_mini
  get "/keys/:id/mini" => "keys#mini", as: :show_key_mini
  get "/settings" => "users#edit", as: :setting
  put "/settings" => "users#update", as: :settings
  get "/upload/app" => "apps#new", as: :new_app
  post "/upload/app" => "apps#create", as: :apps
  post "/upload/key" => "keys#create", as: :keys
  post "/endorsements" => "endorsements#create", as: :endorsements
  post "/github-connect" => "users#github_connect", as: :github_connect
  put "/github-sync" => "users#github_sync", as: :github_sync
end

web/app/views/layouts/application.haml
!!!
%html
  %head
    %title
      GoodApp
      = yield :title
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header
      - if request.subdomain == "api"
        = render "static/api_header"
      - else
        = render "static/header"
    #main.container-fluid
      = render partial: "shared/flash", locals: {flash: flash}
      = yield
    #footer.container-fluid
      = render "static/footer"
    :javascript
      /* declarations */
      #{yield :javascript_declarations}
      /* onload */
      $(function() {
        #{yield :javascript_onload}
      });

web/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Goodapp
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.brand{href: "/"} GoodApp
          %ul#menu-bar.nav
            %li{class: ("active" if @active[:about])}
              = link_to"About", about_path
            %li{class: ("active" if @active[:contact])}
              = link_to "Contact", contact_path
            %li{class: ("active" if @active[:api])}
              = link_to "API", api_path
          %form.navbar-search{action: "/search", method: "get"}
            %input.search-query{type: "text", name: "q", value:params[:q],
              placeholder: "Search by app or dev"}
          .pull-right
            - if current_user
              %ul#user-info.nav
                %li.dropdown{class: ("active" if @active == :user)}
                  %a.dropdown-toggle{href: "#", 'data-toggle' => "dropdown"}
                    = current_user.name
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to "Profile", current_user
                    %li= link_to "Account Settings", edit_user_path(current_user)
                    %li.divider
                    %li= link_to "Logout", logout_path
            - else
              = link_to raw("Login &raquo;"), login_path, class: "btn btn-success"
              = link_to raw("Register &raquo;"), register_path, class: "btn btn-info"
          - if current_user
            - if current_user.is_dev
              = link_to "Upload an App", upload_path, id: "upload-button",
                class: "btn btn-primary pull-right"
            - else
              = button_to "Upgrade to Dev", upgrade_path,
                id: "upgrade-button", class: "btn btn-success pull-right"
    #content.container
      = render partial: "shared/flash", locals: {flash: flash}
      = yield
    #footer.container
      %p
        != "<strong>NULL &copy; 2012</strong> - Project in"
        != "collaboration with <b>Microsoft</b> through UCSB CS189A-B Capstone courses."