web/config/routes.rb
Web::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  # TODO put in authorization so can't hit routes like /settings (obviously)
  constraints subdomain: "api" do
    get "/" => "static#api", as: :api
    get "/users" => "users#index", format: :json
    get "/users/:id" => "users#show", format: :json
    get "/apps/:id" => "apps#show", format: :json
  end
  authenticated :user do
    root to: "static#dashboard"
  end
  root to: "static#index"
  get  "/about" => "static#about", as: :about
  get  "/faq" => "static#faq", as: :faq
  get  "/search" => "static#search", as: :search
  get  "/trust" => "static#trust", as: :trust
  get  "/contact" => "static#contact", as: :contact
  post "/contact" => "static#send_contact_email", as: :send_contact_email
  devise_for :users, controllers: {confirmations: "users/confirmations"}
  resources :users, except: [:edit, :update] do
    # TODO scope keys? so its "/keys/:id"
    resources :keys, except: [:new, :create]
    resources :apps, except: [:new, :create]
  end
  get "/apps/:id" => "apps#show", as: :app
  get "/keys/:id/confirm/:confirmation_token" => "keys#confirm", as: :key_confirmation
  get "/apps/:id/mini" => "apps#mini", as: :show_app_mini
  get "/keys/:id/mini" => "keys#mini", as: :show_key_mini
  get "/settings" => "users#edit", as: :setting
  put "/settings" => "users#update", as: :settings
  get "/upload/app" => "apps#new", as: :new_app
  post "/upload/app" => "apps#create", as: :apps
  post "/upload/key" => "keys#create", as: :keys
  post "/endorsements" => "endorsements#create", as: :endorsements
  post "/github-connect" => "users#github_connect", as: :github_connect
  put "/github-sync" => "users#github_sync", as: :github_sync
end

web/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
   :recoverable, :rememberable, :trackable, :validatable,
   :confirmable

  attr_accessible :name, :about, :email, :password,
    :password_confirmation, :remember_me

  has_many :keys, dependent: :delete_all
  has_many :apps, through: :keys

  has_many :endorsements_as_endorser, foreign_key: :endorser_id, class_name: "Endorsement", dependent: :delete_all
  has_many :endorsements_as_endorsee, foreign_key: :endorsee_id, class_name: "Endorsement", dependent: :delete_all
  has_many :endorsees, through: :endorsements_as_endorser
  has_many :endorsers, through: :endorsements_as_endorsee

  has_one :github_account

  validates_presence_of :name

  auto_strip :name, :email, :about

  def valid_keys
    keys.where(status: 100, proper: true)
  end

  def valid_email_keys
    keys.where(status: 100, style: "email", proper: true)
  end

  def valid_apps
    apps.where(status: 100, proper: true)
  end

  def avg_app_rating
    return 0.0 if self.valid_apps.empty?
    self.valid_apps.map {|a| a.rating}.inject(:+).to_f / self.valid_apps.count
  end

  def max_email_key
    self.valid_email_keys.max {|a, b| (a.rating || 0.0) <=> (b.rating || 0.0)}
  end

  def max_email_key_rating
    mek = max_email_key
    # because key.rating can be nil (if not email key -- *poor* design)
    mek ? (mek.rating || 0.0) : 0.0
  end

  def github_account_rating
    self.github_account ? self.github_account.rating : 0.0
  end

  def base_rating
    base_rating = 0.0
    # GITHUB - 10%
    base_rating += self.github_account_rating * 10.0
    # CORPORATE EMAIL - 10%
    base_rating += self.max_email_key_rating * 10.0
    # APPS
    base_rating += self.avg_app_rating * 40.0
    # weighted to 60%
    base_rating
  end

  # calculated and stored
  def rating
    self.base_rating + (self.endorsement_rating || 0.0) * 30.0
  end

  def has_endorsed?(endorsee)
    self.endorsees.map {|e| e.id}.index(endorsee.id)
  end

  def as_json(opts={})
    {id: self.id, name: self.name, rating: self.rating}
  end

  def self.can_endorse?(endorser, endorsee)
    return false unless endorser && endorsee   # if either is nil
    return false if endorser.id == endorsee.id # endorsing self
    !endorser.has_endorsed?(endorsee)
  end

  def self.most_trusted
    # TODO well, this is horrible (write rating to DB instead of virtual attr)
    User.all.sort {|a, b| b.rating <=> a.rating}[0..5]
  end
end

web/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  def show
    # let devise handle confirmation
    super
    # if the user is confirmed -- let's create their email as a key
    if current_user
      email_key = Key.create({user_id: current_user.id, title: current_user.email,
        kee: current_user.email, status: 100, proper: true,
        style: :email, confirmed_at: Time.now}, without_protection: true)
      email_key.update_rating
    end
  end
end

web/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json {
        @response = []
        unless params[:email].blank?
          email_key = Key.find_by_kee(params[:email])
          unless email_key.nil?
            @response = [User.find(email_key.user_id)]
          end
        end
        render json: @response
      }
    end
  end

  def show
    @user = User.find(params[:id])
    @apps = @user.valid_apps
    @endorsements = @user.endorsements_as_endorsee
    respond_to do |format|
      format.html
      format.json {render json: @user}
    end
  end

  def edit
    # TODO can't decide on this -- this is better for github actions
    session[:tab] ||= :profile
    @user = current_user
  end

  def update
    @user = current_user
    # TODO less hacky?
    session[:tab] = params[:user][:about] ? :profile : :account_settings
    if current_user.update_attributes(params[:user])
      return redirect_to settings_path, notice: "Successfully updated your settings."
    else
      flash.now.alert = "There was an issue in updating your settings."
      return render "edit"
    end
  end

  def github_sync
    session[:tab] = :github
    @user = current_user
    unless @user.github_account
      flash.now.alert = "You can't sync your Github account if it isn't connected!"
      return render "new"
    end
    GithubAccount.sync(@user.id)
    return redirect_to referer, notice: "Your Github account was successfully synced."
  end

  def github_connect
    session[:tab] = :github
    @user = current_user
    @key = Key.find_by_user_id_and_id(current_user.id, params[:key_id])
    unless @key
      flash.now.alert = "You must supply a valid key that you own!"
      return render "edit"
    end
    if params[:username].blank?
      flash.now.alert = "Github username can't be blank!"
      return render "edit"
    end
    unless @key.email_key?
      flash.now.alert = "Connecting your Github account requires an email key."
      return render "edit"
    end
    begin
      json = RestClient.get("https://api.github.com/users/#{params[:username]}")
      github_user = ActiveSupport::JSON.decode(json)
      if github_user["email"] == @key.title
        GithubAccount.sync(current_user.id, github_user["login"])
        return redirect_to settings_path, notice: "Your Github account was successfully connected, #{params[:username]}."
      else
        flash.now.alert = "Your email key does not match the Github email for that username."
        return render "edit"
      end
    rescue RestClient::ResourceNotFound
      flash.now.alert = "That Github username does not exist!"
      return render "edit"
    end
  end
end

web/app/helpers/user_helper.rb
module UserHelper

  def ratingclass(rating)
    case rating.to_i
    when 0..20
      "trust-none"
    when 20..40
      "trust-low"
    when 40..60
      "trust-midlow"
    when 60..80
      "trust-midhigh"
    when 80...100
      "trust-high"
    else
      "notrust"
    end
  end

  def rating(user)
    raw("<span id=\"trust-tag\" class=\"label #{ratingclass(user.rating)}\">#{"%02.2f" % user.rating}</span>")
  end
end

web/app/views/users/_github_form.haml
= form_tag github_connect_path, method: :post, class: "form-horizontal" do |f|
  %fieldset
    %legend= "#{action} your Github Account"
    .control-group
      = label_tag :key_id, "Key", class: "control-label"
      .controls
        = select_tag :key_id, options_for_select(user.valid_email_keys.collect {|k| [k.title, k.id]}, selected: params[:key_id]), {include_blank: true}
        %span.help-inline Used to crosscheck the email on Github.
        %p.help-block
          Haven't uploaded the right email key?
          = link_to "Add it on your settings page", settings_path(anchor: "keys-pane")
    .control-group
      = label_tag :username, "Github Username", class: "control-label"
      .controls
        = text_field_tag :username, params[:username]
    .form-actions
      = submit_tag "#{action} Github Account", class: "btn btn-primary"

web/app/views/users/_profile_form.haml
= form_for user, as: :user, url: settings_path, method: :put, html: {class: "form-horizontal"} do |f|
  %fieldset
    %legend Update your personal information
    .control-group
      = f.label :name, class: "control-label"
      .controls
        = f.text_field :name
    .control-group
      = f.label :about, class: "control-label"
      .controls
        = f.text_area :about, rows: 5, style: "width: 98%"
        %p.help-block This field will be displayed on your profile.
    .form-actions
      = f.submit class: "btn btn-primary"

web/app/views/users/_user.haml
.user.alert.alert-notice
  = link_to rating(user) + " " + user.name, user

web/app/views/users/_user_inline.haml
- title ||= ""
- classes ||= ""
= link_to rating(user) + " " + user.name, user, title: title, class: classes

web/app/views/users/edit.haml
%h1= title "Edit your Settings"

.row-fluid
  .span3.well
    %ul.nav.nav-list
      %li.nav-header MAIN
      %li{class: active?(:profile)}= link_to "Profile", "#profile-pane", 'data-toggle' => "tab"
      %li{class: active?(:account_settings)}= link_to "Account Settings", "#account-settings-pane", 'data-toggle' => "tab"
      %li{class: active?(:keys)}= link_to "Keys & Emails", "#keys-pane", id: "keys-pane-link", 'data-toggle' => "tab"
      %li.nav-header EXTERNAL
      %li{class: active?(:github)}= link_to "Github", "#github-pane", id: "github-pane-link", 'data-toggle' => "tab"
  .span9.tab-content
    #profile-pane.tab-pane{class: active?(:profile)}
      = render partial: "users/profile_form", locals: {user: current_user}
    #account-settings-pane.tab-pane{class: active?(:account_settings)}
      = render partial: "devise/registrations/form", locals: {resource: current_user, method: :put, legend: "Change your settings"}
    #keys-pane.tab-pane{class: active?(:keys)}
      %p.label.label-info Any email you confirm on GoodApp will be added as an email key.
      %ul.nav.nav-tabs
        %li
          %a{'data-toggle' => "tab", href: "#email-key"} Add an Email
        %li.active
          %a{'data-toggle' => "tab", href: "#key-key"} Upload a Key
      .tab-content
        #email-key.tab-pane
          = render partial: "keys/email_form", locals: {user: @user, key: Key.new}
        #key-key.tab-pane.active
          = render partial: "keys/form", locals: {user: @user, key: Key.new}
      - if @user.keys.empty?
        %p.alert.alert-info You have no keys, upload some above.
      - else
        - @user.keys.order("created_at DESC").each do |key|
          = render partial: key, locals: {user: @user}
    #github-pane.tab-pane{class: active?(:github)}
      - if @user.github_account
        -# TODO move these lazy styles into css and add classes
        %div.alert.alert-success{style: "overflow: hidden"}
          = image_tag @user.github_account.avatar_url, class: "pull-left", style: "margin-right: 10px"
          %div{style: "overflow: hidden; zoom: 1"}
            %a{href: "https://github.com/#{@user.github_account.username}"}
              %h2{style: "display: inline"}
                = @user.github_account.username
                -# TODO make button_to and style properly
                = link_to raw('<i class="icon-refresh"></i>'), github_sync_path, method: :put, class: "refresh"
            %p= "#{pluralize(@user.github_account.repos, "Repositories")} | #{pluralize(@user.github_account.watchers, "Watchers")}"
            %p.label.label-success= "+ #{@user.github_account.rating} rating"
      = render partial: "users/github_form", locals: {user: @user, action: @user.github_account ? "Change" : "Connect"}

- content_for :javascript_onload do
  :plain
    $('a[href="' + window.location.hash + '"]').click();
    window.location.hash = "";

web/app/views/users/index.haml
%h1= title "Users"

.users
  = render @users

web/app/views/users/show.haml
%h1
  = rating(@user)
  = @user.name

%canvas#endorse-graph{width: "500", height: "200"}

- unless @user.about.blank?
  %h2 About
  %p.about-section= @user.about

%h2
  = "Endorsements (#{@user.endorsers.count})"
  %span.details Rollover endorsers to see endorsement comment, if any.

- if User.can_endorse?(current_user, @user)
  %p.pull-right{style: "margin: 5px 5px 0 0"}
    %a.btn.btn-success{'data-toggle' => "modal", href: "#endorse-modal"} Endorse
  #endorse-modal.modal.hide.fade
    .modal-header
      %a.close{'data-dismiss' => "modal"} &times;
      %h3= "Endorse #{@user.name}"
    = form_for Endorsement.new, html: {class: "modal-form"} do |f|
      .modal-body
        .control-group
          = f.label :comment, "Comment (optional)"
          = f.text_area :comment, rows: 6, class: "input-block-level"
          %p.help-block.warning
            Careful, this action is not reversible (an endorsement is forever).
        = f.hidden_field :endorsee_id, value: @user.id
      .modal-footer
        = f.submit "Submit Endorsement", class: "btn btn-primary"

- if @endorsements.empty?
  %p.alert.alert-info No endorsements.
- else
  .alert.alert-info
    %ul.endorsements
      - @endorsements.each do |endorsement|
        %li= render endorsement

-# TODO only show most recent versions (group by aid and select last created_at)
%h2
  = "Uploaded Apps (#{@apps.count})"
- if @apps.empty?
  %p.alert.alert-info No apps.
- else
  - @apps.each do |app|
    = render app

- content_for :javascript_onload do
  :plain
    var graph = new Graph();
    var black = {color: "black"};
    var #{@user.name.gsub(/ /, "")} = graph.newNode({label: "#{@user.name}"});
  - (@user.endorsers + @user.endorsees - [@user]).each do |user|
    :plain
      var #{user.name.gsub(/ /, "")} = graph.newNode({label: "#{user.name}"});
  - @user.endorsers.each do |endorser|
    - endorser_name = endorser.name.gsub(/ /, "")
    :plain
      graph.newEdge(#{endorser_name}, #{@user.name.gsub(/ /, "")}, black);
  - @user.endorsees.each do |endorsee|
    - endorsee_name = endorsee.name.gsub(/ /, "")
    :plain
      graph.newEdge(#{@user.name.gsub(/ /, "")}, #{endorsee_name}, black);
  :plain
    var springy = $("#endorse-graph").springy({graph: graph});