web/config/routes.rb
Web::Application.routes.draw do
  mount Resque::Server.new, at: "/resque"
  # TODO put in authorization so can't hit routes like /settings (obviously)
  constraints subdomain: "api" do
    get "/" => "static#api", as: :api
    get "/users" => "users#index", format: :json
    get "/users/:id" => "users#show", format: :json
    get "/apps/:id" => "apps#show", format: :json
  end
  authenticated :user do
    root to: "static#dashboard"
  end
  root to: "static#index"
  get  "/about" => "static#about", as: :about
  get  "/faq" => "static#faq", as: :faq
  get  "/search" => "static#search", as: :search
  get  "/trust" => "static#trust", as: :trust
  get  "/contact" => "static#contact", as: :contact
  post "/contact" => "static#send_contact_email", as: :send_contact_email
  devise_for :users, controllers: {confirmations: "users/confirmations"}
  resources :users, except: [:edit, :update] do
    # TODO scope keys? so its "/keys/:id"
    resources :keys, except: [:new, :create]
    resources :apps, except: [:new, :create]
  end
  get "/apps/:id" => "apps#show", as: :app
  get "/keys/:id/confirm/:confirmation_token" => "keys#confirm", as: :key_confirmation
  get "/apps/:id/mini" => "apps#mini", as: :show_app_mini
  get "/keys/:id/mini" => "keys#mini", as: :show_key_mini
  get "/settings" => "users#edit", as: :setting
  put "/settings" => "users#update", as: :settings
  get "/upload/app" => "apps#new", as: :new_app
  post "/upload/app" => "apps#create", as: :apps
  post "/upload/key" => "keys#create", as: :keys
  post "/endorsements" => "endorsements#create", as: :endorsements
  post "/github-connect" => "users#github_connect", as: :github_connect
  put "/github-sync" => "users#github_sync", as: :github_sync
end

web/app/views/apps/_app.haml
- haml_tag_if(!defined?(wrapper), :div, id: "app-#{app.id}", class: "app") do
  - status = app.proper ? "success" : "danger"
  .alert{class: "alert-#{status}"}
    - if !app.proper
      .progress.progress-danger.progress-striped
        .bar{style: "width: #{app.status.to_s}%"}
          %p= app.state
    - if app.title
      %h3
        = show_platform(app.platform)
        = link_to_if app.status == 100, app.title, [app.user, app]
        - if app.version
          %span.label.label-info.header-inline= app.version
    - if app.status < 100
      .progress.progress-success.progress-striped.active
        .bar{style: "width: #{app.status.to_s}%"}
          %p= app.state
      - if !defined? js
        - content_for :javascript_onload do
          :plain
            refreshMini("app", #{app.id});
    %span
      %em= "uploaded " + distance_of_time_in_words_to_now(app.created_at) + " ago"

web/app/views/apps/_form.haml
= form_for app, html: {multipart: true, class: "form-horizontal"} do |f|
  %fieldset
    %legend Upload a signed app
    .control-group
      = f.label :key_id, class: "control-label"
      .controls
        = f.select :key_id, user.valid_keys.collect {|k| [k.title, k.id]}, {include_blank: true}
        %span.help-inline Used to check the signature on the app.
        %p.help-block
          Haven't uploaded the right key?
          = link_to "Add it on your settings page", settings_path(anchor: "keys-pane")
    .control-group
      = label_tag :file, 'File', class: "control-label"
      .controls
        = file_field_tag :file
        %span.help-inline.label Only Android .apk files supported (for Alpha).
        %p.help-block
          We only grab
          %strong metadata
          from your app and
          %strong scan it
          before
          %strong deleting
          the uploaded data from our servers.
    .form-actions
      = f.submit "Upload App", class: "btn btn-primary"

web/app/views/apps/mini.haml
= render partial: @app, locals: {wrapper: false}

web/app/views/apps/new.haml
%h1= title "Apps"

- if @user.valid_keys.empty?
  %p.alert.alert-warning
    You need to
    = link_to "upload a key", settings_path(anchor: "keys-pane")
    to be able to upload apps.
- else
  = render partial: "apps/form", locals: {user: @user, app: @app}
  - if @user.apps.empty?
    %p.alert.alert-info You have no apps, upload some above.
  - else
    %h2 App Upload History
    .apps
      - @apps.limit(4).each do |app|
        = render app

web/app/views/apps/show.haml
%h1
  = show_platform(@root_app.platform)
  = title @root_app.title

%h2
  -# TODO support more than one dev
  = "Developers (1)"
-# if @developers.empty?
  %p.alert.alert-info No developers.
-# else
  .alert.alert-info
    %ul.developers
      - @developers.each do |developer|
        %li= render partial: "users/user_inline", locals: {user: developer}
.alert.alert-info
  %ul.developers
    %li= render partial: "users/user_inline", locals: {user: @app.user}

%h2
  = "Uploaded Versions (#{@app_versions.count})"
%ul.nav.nav-tabs
  - @app_versions[0..-2].each do |app|
    %li{class: ("active" if app.id == @app.id)}
      %a{'data-toggle' => "tab", href: "#app#{app.id}"}
        %span.label= app.version
  - app = @app_versions[-1]
  %li{class: ("active" if app.id == @app.id)}
    %a{'data-toggle' => "tab", href: "#app#{app.id}"}
      %span.label.label-info= app.version
.tab-content
  - @app_versions.each do |app|
    .tab-pane{id: "app#{app.id}", class: ("active" if app.id == @app.id)}
      %h3= app.title